version: "2"
services:
  postgres:
    image: postgres:9.5
    enviroment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - postgres-conf:/etc/postgresql
      - postgres-logs:/var/log//postgresql
    networks:
      - dashboard-network
  dashboard:
    build: .
    command: supervisord
    volumes:
      - .:/code/
      - .:/code/media
    enviroment:
      - C_FORCE_ROOT=true
      - DB_PASSWORD: postgres
      - DB_NAME: dashboard
    ports:
      - "8000:8000"
    networks:
      - dashboard-network
    depends_on:
      - postgres
volumes:
  postgres-data:
  postgres-conf:
  postgres-logs:
networks:
  dashboard-network:
    driver: bridge
